const state={catalog:null,selected:null};
const $=id=>document.getElementById(id);
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
async function api(path,options={}){const response=await fetch(path,{cache:"no-store",...options});const body=await response.json();if(!response.ok)throw new Error(body.error||response.statusText);return body}
function fields(){return Object.fromEntries(new FormData($("productForm")).entries())}
function fill(product={}){const form=$("productForm");const values={...product,...(product.hardware||{}),ssh:product.operations?.ssh||"",notes:product.operations?.notes||""};[...form.elements].forEach(control=>{if(control.name)control.value=values[control.name]??""});state.selected=product.id||null;$("saveState").textContent="";renderList()}
function renderList(){const list=$("productList");list.innerHTML=state.catalog.products.map(product=>`<button class="manage-item${state.selected===product.id?" active":""}" data-id="${esc(product.id)}"><strong>${esc(product.name)}</strong><small>${esc(product.category)} · ${esc(product.status)}</small></button>`).join("");list.querySelectorAll("[data-id]").forEach(button=>button.onclick=()=>fill(state.catalog.products.find(product=>product.id===button.dataset.id)))}
function blank(){fill({status:"Draft",hardware:{},operations:{}})}
async function init(){state.catalog=await api("/api/products");const select=$("productForm").elements.category;select.innerHTML=state.catalog.categories.map(category=>`<option value="${esc(category.id)}">${esc(category.name_zh)} · ${esc(category.name)}</option>`).join("");renderList();const id=new URLSearchParams(location.search).get("id");fill(state.catalog.products.find(product=>product.id===id)||state.catalog.products[0]||{})}
$("productForm").addEventListener("submit",async event=>{event.preventDefault();const data=fields();const current=state.catalog.products.find(item=>item.id===state.selected)||{};const benchmarkName=["asus-rog-ai-max395","asus-tuf-gaming-ai-max392"].includes(data.id)?"Benchmark_Result":"Benchmark";const product={id:data.id,category:data.category,name:data.name,positioning:data.positioning,status:data.status,summary:data.summary,folder:data.folder,hardware:{...(current.hardware||{}),CPU:data.CPU,GPU:data.GPU,Memory:data.Memory,Storage:data.Storage,OS:data.OS},models:current.models||[],documents:{folder:`${data.folder}/Documents`,public_folder:`${data.folder}/Documents/Public`},benchmark:{...(current.benchmark||{}),folder:`${data.folder}/${benchmarkName}`,public_folder:`${data.folder}/${benchmarkName}/Public`,metrics:current.benchmark?.metrics||["TTFT","TPOT","Throughput"]},scripts:{folder:`${data.folder}/Scripts`,public_folder:`${data.folder}/Scripts`},operations:{ssh:data.ssh,notes:data.notes},publish:{enabled:true}};try{const result=await api("/api/products/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({original_id:state.selected,product})});state.catalog=result.catalog;state.selected=product.id;renderList();$("saveState").textContent="已儲存"}catch(error){$("saveState").textContent=error.message}});
$("newProduct").onclick=blank;
$("scanProduct").onclick=async()=>{const id=$("productForm").elements.id.value;if(!id)return;$("scanResult").innerHTML='<div class="note">掃描中…</div>';try{const [docs,bench,scripts]=await Promise.all([api(`/api/scan?product=${encodeURIComponent(id)}&kind=documents`),api(`/api/scan?product=${encodeURIComponent(id)}&kind=benchmark`),api(`/api/scan?product=${encodeURIComponent(id)}&kind=scripts`)]);$("scanResult").innerHTML=`<h3>掃描結果</h3><div class="metric-grid"><div class="metric"><label>Documents</label><strong>${docs.items.length} files</strong></div><div class="metric"><label>Benchmark</label><strong>${bench.items.length} files</strong></div><div class="metric"><label>Scripts</label><strong>${scripts.items.length} files</strong></div><div class="metric"><label>Public folders</label><strong>僅 Public 子資料夾會發布</strong></div></div>`}catch(error){$("scanResult").innerHTML=`<div class="note">${esc(error.message)}</div>`}};
$("exportPublic").onclick=async()=>{const button=$("exportPublic");button.disabled=true;button.textContent="產生中…";try{const result=await api("/api/export",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});alert(`GitHub Pages 已產生：${result.output}\n公開檔案：${result.files} 個`)}catch(error){alert(error.message)}finally{button.disabled=false;button.textContent="產生 GitHub Pages"}};
init().catch(error=>{$("saveState").textContent=`無法開啟管理功能：${error.message}`});
